### ISSUE TITLE
swivel on the spot death

### ISSUE THREAD

**Issue by harry-wood** [xurxodiz/snake#2]
You can somehow die by steering your snake too quickly to make it swivel on the  spot

e.g, you're moving upwards  you hit → and then ↓  very quickly.   You die.

I guess the code should track the direction the snake is moving in, but only update this when the snake has started moving at least one square in that direction.

**Comment by xurxodiz** [comment]
Great idea! I won't work on it anymore, but I'll keep it in mind for future projects. Thanks.
