### ISSUE TITLE
click to start new game

### ISSUE THREAD

**Issue by harry-wood** [xurxodiz/snake#3]
It's annoying the way you have to click in the square to start a game, since you end up with the mouse pointer in the way.

I thought maybe it was done this way to get the browser to activate the widget somehow but...

it's doubly annoying that you have to do this _between_ each game. Should be able to press space/enter to restart

**Comment by bjskistad** [comment]
+1

**Comment by xurxodiz** [comment]
Closing due to PR #5 fixing this :)
